"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my/our honor, <Anthony Dezdha> and <FULL NAME>, this
programming assignment is my own work and I have not provided this code to
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1:AD54489
UT EID 2:
"""

def group_sum(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to the
    given target.

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    #base: hit all nums
    if start >= len(nums):
        return target == 0
    #recursive: nums, adding da current num
    if group_sum(start+1, nums, target-nums[start]):
        return True
    #recursive: n/nums not adding da current num, hence our target being target :)
    if group_sum(start+1, nums, target):
        return True
    #allfail: return False
    return False

# TODO: Modify this function. You may delete this comment when you are done.
def group_sum_6(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to the
    given target. Additionally, if there is are 6's present in the array, they must all
    be chosen.

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    


def group_no_adj(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to
    the given target. Additionally, if a value is chosen, the value immediately after
    (the value adjacent) cannot be chosen.

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    #base case: if we hit all nums
    if start >= len(nums):
        return target == 0
    # move reursion 2 steps ahead, and over +1
    if group_no_adj(start + 2, nums, target - nums[start]):
        return True
    #when numstart not chosen, we move 1 step next to decide next elemetn
    if group_no_adj(start + 1, nums, target):
        return True
    #all fail measure :( #sad
    return False

# TODO: Modify this function. You may delete this comment when you are done.
def group_sum_5(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to
    the given target. Additionally, if a multiple of 5 is in the array, it must be included
    If the value immediately following a multiple of 5 if 1, it must not be chosen

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """



def group_sum_clump(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to
    the given target. Additionally, if there is a group of identical numbers in succession,
    they must all be chosen, or none of them must be chosen.
    EX: [1, 2, 2, 2, 5, 2], all three of the middle 2's must be chosen, or none of them must be
    chosen to be included in the sum. One loop is allowed to check for identical numbers.

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    #mindmap, hogg
    #def backtrack(i):
    # if i == n:
    #    res.append(sol[:])
    #   return
    
    # Don't pick nums[i]
    # backtrack(i + 1)
    
    # Pick nums[i]
    #sol.append(nums[i])
    #backtrack(i + 1)
    #sol.pop()

    #if we hit all nums base case:
    #if start >= len(nums):
    #   return target == 0
    
    #i == n, end condt. base
    #move i forward by size of consec clump, skip, or pick
    if start >= len(nums):
        return target == 0 #sum, base
    #clump
    length, clump, startIN = nums[start], 0, start
    while startIN < len(nums) and nums[startIN] == length:
        clump += nums[startIN]
        startIN += 1
    #chosen
    if group_sum_clump(startIN, nums, target - clump):
        return True
    #notchosen
    if group_sum_clump(startIN, nums, target):
        return True
    #all fail
    return False
    
    

# TODO: Modify this function
def split_array(nums):
    """
    Given a list of ints, determine if the numbers can be split evenly into two groups
    The sum of these two groups must be equal
    Write a recursive helper to call from this function

    pre: len(nums) >= 0, nums will only contain ints
    post: return True if nums can be split, False otherwise
    """
    


def split_odd_10(nums):
    """
    Given a list of ints, determine if the numbers can be split evenly into two groups
    The sum of one group must be odd, while the other group must be a multiple of 10
    Write a recursive helper to call from this function

    pre: len(nums) >= 0, nums will only contain ints
    post: return True if nums can be split, False otherwise
    """
    #base case: for if 2 groups satisfy the condt of one odd and other mult of 10
    #recursive helper function, to call
    def helperfunct(index=0, gr1=0, gr2=0):
        if index >= len(nums):
            return ((gr1 % 2 == 1 and gr2 % 10 == 0) or (gr2 % 2 == 1 and gr1 % 10 == 0))
        # 1 group is odd and one multiple!!
        #sum of one group odd
        #sum of one group multiple of 10
        if helperfunct(index +1, gr1 + nums[index], gr2):
            return True
        if helperfunct(index +1, gr1, gr2 + nums[index]):
            return True
        #all fail situation -_-
        return False
    return helperfunct()

 


# TODO: Modify this function. You may delete this comment when you are done.
def split_53(nums):
    """
    Given a list of ints, determine if the numbers can be split evenly into two groups
    The sum of these two groups must be equal
    Additionally, all multiples of 5 must be in one group, and all multiples of 3 (and not 5)
    must be in the other group
    Write a recursive helper to call from this function

    pre: len(nums) >= 0, nums will only contain ints
    post: return True if nums can be split, False otherwise
    """
